export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
// export const USER_SIGNIN = "USER_SIGNIN";

// export const FETCH_USER = "FETCH_USER";
// export const FETCH_USER_PROFILE = "FETCH_USER_PROFILE";
 
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCT_VARIANTS = "FETCH_PRODUCT_VARIANTS";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_LIST = "UPDATE_PRODUCT_LIST";
 
export const FETCH_CUSTOMER = "FETCH_CUSTOMER";
export const FETCH_CUSTOMERS = "FETCH_CUSTOMERS";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";

export const FETCH_DEAL = "FETCH_DEAL";
export const FETCH_DEALS = "FETCH_DEALS";
export const UPDATE_DEAL = "UPDATE_DEAL";
 
export const FETCH_DEAL_PRODUCT = "FETCH_DEAL_PRODUCT";
export const FETCH_DEAL_PRODUCTS = "FETCH_DEAL_PRODUCTS";
export const UPDATE_DEAL_PRODUCT = "UPDATE_DEAL_PRODUCT";
 
export const FETCH_ORDER = "FETCH_ORDER";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const ORDER_SUMMARY = "ORDER_SUMMARY";
 
export const FETCH_ORDER_RETURN = "FETCH_ORDER_RETURN";
export const FETCH_ORDER_RETURNS = "FETCH_ORDER_RETURNS";
export const UPDATE_ORDER_RETURN = "UPDATE_ORDER_RETURN";
export const UPDATE_ORDER_RETURN_LIST = "UPDATE_ORDER_RETURN_LIST";
export const CREATE_ORDER_RETURN = "CREATE_ORDER_RETURN";
export const DELETE_ORDER_RETURN = "DELETE_ORDER_RETURN";
 
export const FETCH_ORDER_FULFILLMENT = "FETCH_ORDER_FULFILLMENT";
export const FETCH_ORDER_FULFILLMENTS = "FETCH_ORDER_FULFILLMENTS";
export const CREATE_ORDER_FULFILLMENT = "CREATE_ORDER_FULFILLMENT";
export const DELETE_ORDER_FULFILLMENT = "DELETE_ORDER_FULFILLMENT";
export const UPDATE_ORDER_FULFILLMENT = "UPDATE_ORDER_FULFILLMENT";
 
export const FETCH_WINNER = "FETCH_WINNER";
export const FETCH_WINNERS = "FETCH_WINNERS";
export const UPDATE_WINNER = "UPDATE_WINNER";
 
export const FETCH_DEAL_ENTRY = "FETCH_DEAL_ENTRY";
export const FETCH_DEAL_ENTRIES = "FETCH_DEAL_ENTRIES";
export const UPDATE_DEAL_ENTRY = "UPDATE_DEAL_ENTRY";
 
export const USER_INFO = "USER_INFO";
export const USER_SIGNIN = "USER_SIGNIN";
export const USER_SIGNUP = "USER_SIGNUP";
export const PRODUCTS_LIST = "PRODUCTS_LIST";
export const PRODUCT_CATEGORIES = "PRODUCT_CATEGORIES";
export const PRODUCT_CART = "PRODUCT_CART";
export const PRODUCT_CART_DELETE = "PRODUCT_CART_DELETE";
export const PRODUCT_CART_TOTAL = "PRODUCT_CART_TOTAL";
export const USER_ORDER_LIST = "USER_ORDER_LIST";
export const PRODUCT_BILLING = "PRODUCT_BILLING";
export const PRODUCT_REFUND = "PRODUCT_REFUND";
export const PRODUCT_WISHLIST = "PRODUCT_WISHLIST";
export const PRODUCT_WISHLIST_DELETE = "PRODUCT_WISHLIST_DELETE"; 